### ISSUE TITLE
OS Variable Before Date

### ISSUE THREAD

**Issue by Ryushin** [Josef-Friedrich/check_zpool_scrub#10]
Running Devuan Ascii Linux.  Everytime the command is run, it threw an error:
date: invalid option -- 'j'

Had to move the "OS=$(uname)" before the Date Functions. 

Running version 1.3.

**Comment by Ryushin** [comment]
One other thing, should a pool that has never had a scrub be in a critical state instead of unknown?

**Comment by Ryushin** [comment]
The unknown state for a pool that has never been scrubed, does not state which pool is the problem.

./check_zpool_scrub -w 5184000 -c 7776000
UNKNOWN: The pool has never had a scrub. OK: The last scrub on zpool 'netshares' was performed on 2019-06-10.01:27:48. OK: The last scrub on zpool 'rpool' was performed on 2019-06-09.08:59:32. OK: The last scrub on zpool 'virtpool' was performed on 2019-06-09.09:32:27. | warning=5184000 critical=7776000 netshares_last_ago=2537479 netshares_progress=100 netshares_speed=0 netshares_time=0 rpool_last_ago=2596775 rpool_progress=100 rpool_speed=0 rpool_time=0 virtpool_last_ago=2594800 virtpool_progress=100 virtpool_speed=0 virtpool_time=0

**Comment by Josef-Friedrich** [comment]
The OS variable issue was already fixed in the master branch see: f7344844b60c6c2ddc5ed4ee3eaf2262556a9310. I bumped an new version: 1.4

**Comment by Josef-Friedrich** [comment]
I’m not sure about your CRITICAL versus UNKOWN proposal: A recently created pool for example without a scrub is in my opinion not critical

**Comment by Ryushin** [comment]
To me if a pool has never had a scrub, that would be critical.  A pool could have never ever had a scrub.  I understand the new pool opinion though.  I'd rather get the alert.  The issue still exists that if the pool had never had a scrub, the name of the pool should be given.  In my case, i created a new pool called dbpool a week ago.  

Very useful check you have created and I appreciate it.

**Comment by Josef-Friedrich** [comment]
Indeed the pool name was missing: please try 14c8690c4ec08309268676e900879a8a07883cb8

**Comment by Ryushin** [comment]
Thanks for the fix.  Looks good.
